### PR TITLE
Add work experience list

### PR DESCRIPTION
**Pull request by JoeyStk**
This PR is still a work in progress. The first commit only adds completely raw logic to the experience list. There is no still as for now

### CODE REVIEW

**Comment by JoeyStk** [comment]
@amikable-tech I didn't succeed to get Tailwind running. Could you please have a look at this PR and maybe give me a hint of what is not working? :)

**Comment by to-sta** [comment]
Hi @JoeyStk, i checked your PR and found some minor issues:

While running the django server i get the following error:
```bash
"GET /cv_generator/main/static/output.css HTTP/1.1" 404 2355"
```
This means django cannot find the output.css file. I would suggest to use the static file tag 😃.

```html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CV Generator</title>
    <link href="{% static "output.css" %}" rel="stylesheet">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>
```
You also want to point to the html files where you use tailwind css classes in the content option:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./main/templates/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```
I tried it and it work :)

**Comment by JoeyStk** [comment]
@to-sta Thank you very much! Your suggestions were very helpful! I applied them and now the PR should properly work! Please don't forget to create a user and log in before you use the bulk action

**Comment by JoeyStk** [comment]
> Should the page only show the work experience of the user that is logged in or all

Oh, that is a good point. It should of course only show the work experience of the logged in user. I will add another commit for this

> Any specific reason why you choose a models.CharField for date? I would usually use a models.DateField for it.

Generally I agree. In this case I prefered to use the CharField since I thought it would be better to leave the format to the user and I that it was just easier to have one CharField instead of two DateFields. But I'm having second thoughts about this as well

**Comment by JoeyStk** [comment]
@to-sta Thank you for your review. The requested changes should be applied. As soon as this is approved, I will have a look at solving the merge conflicts

**Review by to-sta — APPROVED** [review]
Looks good to me :)

**Pull request merged**
